<a href="https://colab.research.google.com/github/MAITREED03/gen_ai1/blob/main/data_representation_and_vectorization1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd. DataFrame({"text": ["my name is tanya",
                             "i am a data scientist",
                             "i dont know java",
                             "i dont like cooking "], "output":[1,1,0,0]})

In [ ]:
df

text  output
0       my name is tanya       1
1  i am a data scientist       1
2       i dont know java       0
3   i dont like cooking        0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
bow

<4x12 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [ ]:
#vocabulary

In [ ]:
print(cv.vocabulary_)

{'my': 8, 'name': 9, 'is': 4, 'tanya': 11, 'am': 0, 'data': 2, 'scientist': 10, 'dont': 3, 'know': 6, 'java': 5, 'like': 7, 'cooking': 1}


In [ ]:
bow.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 0 1 0 0 0 1 1 0 1]]
[[1 0 1 0 0 0 0 0 0 0 1 0]]
[[0 0 0 1 0 1 1 0 0 0 0 0]]


In [ ]:
## for new data
cv.transform(["i love deep learning"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
X = bow.toarray()
Y = df["output"]

In [ ]:
X

array([[0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
Y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

In [ ]:
## N gram

In [ ]:
df = pd. DataFrame({"text": ["my name is tanya",
                             "i am a data scientist",
                             "i dont know java",
                             "i dont like cooking "], "output":[1,1,0,0]})

In [ ]:
df

text  output
0       my name is tanya       1
1  i am a data scientist       1
2       i dont know java       0
3   i dont like cooking        0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
print(cv.vocabulary_)

{'my name': 7, 'name is': 8, 'is tanya': 4, 'am data': 0, 'data scientist': 1, 'dont know': 2, 'know java': 5, 'dont like': 3, 'like cooking': 6}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 0 1 0 0 1 1]]
[[1 1 0 0 0 0 0 0 0]]
[[0 0 1 0 0 1 0 0 0]]


In [ ]:
##TF-IDF(Term frequency- Inverse document frequency)

In [ ]:
df = pd. DataFrame({"text": ["my name is tanya",
                             "i am a data scientist",
                             "i dont know java",
                             "i dont like cooking "], "output":[1,1,0,0]})

In [ ]:
df

text  output
0       my name is tanya       1
1  i am a data scientist       1
2       i dont know java       0
3   i dont like cooking        0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
arr = tfid.fit_transform(df['text']).toarray()

In [ ]:
arr

array([[0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.        , 0.        , 0.        , 0.5       , 0.5       ,
        0.        , 0.5       ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        ],
       [0.        , 0.        , 0.        , 0.48693426, 0.        ,
        0.61761437, 0.61761437, 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.61761437, 0.        , 0.48693426, 0.        ,
        0.        , 0.        , 0.61761437, 0.        , 0.        ,
        0.        , 0.        ]])

In [ ]:

print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.51082562 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073]
